AdGroupServiceBiddingStrategyConfiguration:
  title: AdGroupServiceBiddingStrategyConfiguration
  type: object
  nullable: true
  properties:
    biddingScheme:
      $ref: 'AdGroupServiceBiddingScheme.yaml#/AdGroupServiceBiddingScheme'
    portfolioBiddingId:
      type: integer
      nullable: true
      format: int64
      description: |
        <div lang="ja">ポートフォリオ入札IDです。<br>
        このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div>
        <div lang="en">Portfolio bidding ID.<br>
        Although this field will be returned in the response, it will be ignored on input.</div>
    portfolioBiddingName:
      type: string
      nullable: true
      description: |
        <div lang="ja">ポートフォリオ入札名です。<br>
        ADD時、このフィールドは無視されます。<br>
        ※50文字以内になります。</div>
        <div lang="en">Portfolio bidding name.<br>
        This field will be ignored in ADD operation.<br>*
        Up to 50 characters.</div>
  description: |
    <div lang="ja">AdGroupServiceBiddingStrategyConfigurationオブジェクトは、自動入札設定方法を表します。<br>
    </div>
    <div lang="en">AdGroupServiceBiddingStrategyConfiguration object describes Auto Bidding setting.<br>
    </div>
