CampaignServiceGoalConfigLevel:
  type: string
  nullable: true
  enum:
  - ACCOUNT
  - CAMPAIGN
  - UNKNOWN
  title: CampaignServiceGoalConfigLevel
  description: |
    <div lang="ja">CampaignServiceGoalConfigLevel、最適化に使用するコンバージョンです。<br>
    ADD時およびSET時、このフィールドはconversionSetting配下では必須となります。</div>
    <div lang="en">CampaignServiceGoalConfigLevel is conversion action for optimization.<br>
    Under conversionSetting, this field is required in ADD and SET operation.</div>
    <dl class=term>
      <dt class="term__item">ACCOUNT</dt>
      <dd class="term__desc"><span lang="ja">アカウント単位です。</span><span lang="en">Account</span></dd>
      <dt class="term__item">CAMPAIGN</dt>
      <dd class="term__desc"><span lang="ja">キャンペーン単位です。</span><span lang="en">Campaign</span></dd>
      <dt class="term__item">UNKNOWN</dt>
      <dd class="term__desc"><span lang="ja">未知の値です。</span><span lang="en">Unknown value.</span></dd>
    </dl>
